# Generated by Django 4.2.5 on 2023-09-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sihpredict', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reciepe',
            new_name='Articles',
        ),
    ]
