# Generated by Django 4.2.5 on 2023-09-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihpredict', '0003_article_receipe_delete_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField()),
                ('content', models.TextField()),
                ('urls', models.TextField()),
                ('source', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='article',
        ),
        migrations.DeleteModel(
            name='Receipe',
        ),
    ]
